[package]
name = "pinger"
version = "0.8.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"
license = "MIT"
description = "A small cross-platform library to execute the ping command and parse the output"
repository = "https://github.com/orf/pinger/"

[dependencies]
anyhow = "1.0.69"
regex = "1.7.1"
lazy_static = "1.4.0"
thiserror = "1.0.39"

[target.'cfg(windows)'.dependencies]
winping = "0.10.1"
dns-lookup = "1.0.8"

[dev-dependencies]
os_info = "3.6.0"
