on:
  push:
    tags:
      - 'gping-v*'
      - '!gping-v*-post*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: gping
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
